[wso2.devportal_service]
DEVPORTAL_PORT = 9443
[wso2.devportal_service.datasourceConfiguration]
description = "Database for devportal"
url = "jdbc:postgresql://localhost:5432/APKDB"
host = "localhost"
port = 5432
databaseName = "APKDB"
username = "admin"
password = "admin"
validationTimeout = 250
testQuery = "SELECT 1"
driver = "org.postgresql.Driver"
[wso2.devportal_service.throttleConfig.blockCondition]
enabled = true