apiVersion: dp.wso2.com/v1alpha1
kind: APIPolicy
metadata:
  name: backend-jwt-token-policy
  namespace: apk
spec:
  override:
    backendJwtToken:
      isEnabled: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: API
    name: http-bin-api