apiVersion: dp.wso2.com/v1alpha2
kind: API
metadata:
  labels:
    api-name: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
    api-version: 356a192b7913b04c54574d18c28d46e6395428ab
    managed-by: apk
    organization: 2e14f1a627e0f7388df2efa85fba6816ac25f0941
    revisionID: "1"
  name: 2476a37684aa6eac966ba4961de408e4b6097d32
  namespace: apk
spec:
  apiName: api1
  apiType: REST
  apiVersion: "1"
  basePath: /api1
  definitionFileRef: 2476a37684aa6eac966ba4961de408e4b6097d31-definition
  definitionPath: /definition
  isDefaultVersion: false
  organization: carbon.super
  production:
  - routeRefs:
    - 2476a37684aa6eac966ba4961de408e4b6097d31-production-httproute-1
  sandbox:
  - routeRefs:
    - 2476a37684aa6eac966ba4961de408e4b6097d31-sandbox-httproute-1
  systemAPI: false
---
apiVersion: v1
binaryData:
  definition: H4sIAAAAAAAA/62SPW7DMAyFr1JwLALbSTdfoUOHolOQQZDpioBsCSLdIjF895Iy2rGTNeiHj+8Th7dCyji7TNDDS9M1Zzg9Ac1jgn4FIYmogiCL1b+wMKVZK2fY9M3ol0Jyh/66woCjW6Lo/bbdVMxOAhulfbb9E8WOgpzTzFiVS9fZMSD7Qll29NsrbP/DTc3LsbjEh/IGjCh46IROfDgMWHWfJiXhLBX12/3uA047/c+jUbhnS0Jyi4SLZWGM6bs20ZQjeapdpqZCD2eTfJSojiCSuW9by1CjP5qXvYbOzNu+fgA02l2YhQIAAA==
kind: ConfigMap
metadata:
  name: 2476a37684aa6eac966ba4961de408e4b6097d31-definition
  namespace: apk
  resourceVersion: "135907"
  uid: 8d5657ef-d425-481e-b1b5-eb1ea9f24976
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: 2476a37684aa6eac966ba4961de408e4b6097d31-production-httproute-1
  namespace: apk
spec:
  hostnames:
  - default.gw.wso2.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: wso2-apk-default
    sectionName: httpslistener
  rules:
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-ec604b3c95d650b761dfbc185022f5d772397187-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: GET
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-ec604b3c95d650b761dfbc185022f5d772397187-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: PUT
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-ec604b3c95d650b761dfbc185022f5d772397187-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: POST
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-ec604b3c95d650b761dfbc185022f5d772397187-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: DELETE
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-ec604b3c95d650b761dfbc185022f5d772397187-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: PATCH
      path:
        type: RegularExpression
        value: (.*)
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: 2476a37684aa6eac966ba4961de408e4b6097d31-sandbox-httproute-1
  namespace: apk
spec:
  hostnames:
  - sandbox.default.gw.wso2.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: wso2-apk-default
    sectionName: httpslistener
  rules:
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-5df3c49a82265e2367d4606ff28bd54d3af0ffdb-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: GET
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-5df3c49a82265e2367d4606ff28bd54d3af0ffdb-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: PUT
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-5df3c49a82265e2367d4606ff28bd54d3af0ffdb-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: POST
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-5df3c49a82265e2367d4606ff28bd54d3af0ffdb-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: DELETE
      path:
        type: RegularExpression
        value: (.*)
  - backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: backend-5df3c49a82265e2367d4606ff28bd54d3af0ffdb-api
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replaceFullPath: \1
          type: ReplaceFullPath
    - extensionRef:
        group: dp.wso2.com
        kind: RateLimitPolicy
        name: resource-2476a37684aa6eac966ba4961de408e4b6097d31
      type: ExtensionRef
    - extensionRef:
        group: dp.wso2.com
        kind: APIPolicy
        name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
      type: ExtensionRef
    matches:
    - method: PATCH
      path:
        type: RegularExpression
        value: (.*)
---
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: backend-ec604b3c95d650b761dfbc185022f5d772397187-api
  namespace: apk
spec:
  basePath: ""
  protocol: http
  services:
  - host: local
    port: 80
---
apiVersion: dp.wso2.com/v1alpha1
kind: Backend
metadata:
  name: backend-5df3c49a82265e2367d4606ff28bd54d3af0ffdb-api
  namespace: apk
spec:
  basePath: ""
  protocol: http
  services:
  - host: local
    port: 80
---
apiVersion: dp.wso2.com/v1alpha2
kind: APIPolicy
metadata:
  name: 2476a37684aa6eac966ba4961de408e4b6097d31-resource-policy
  namespace: apk
spec:
  default:
    cORSPolicy:
      accessControlAllowHeaders:
      - authorization
      - Access-Control-Allow-Origin
      - Content-Type
      - SOAPAction
      accessControlAllowMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
      accessControlAllowOrigins:
      - '*'
    subscriptionValidation: true
  targetRef:
    group: dp.wso2.com
    kind: Resource
    name: 2476a37684aa6eac966ba4961de408e4b6097d31
