[wso2.backoffice_service.backoffice]
BACKOFFICE_PORT = 9443

# Sample configurations
[wso2.backoffice_service.backoffice.datasourceConfiguration]
description = "APK DB"
url = "jdbc:postgresql://localhost:5432/apkdb"
username = "apimadmin"
password = "apimadmin"
validationTimeout = 30000
testQuery = "SELECT 1"


