apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-definition-runtime-ds
  namespace: {{ .Release.Namespace }}
data:
  swagger.yaml: |
    swagger: "2.0"
    info:
      description: "This is a sample server Petstore server."
      version: 1.0.0
      title: runtime-domain-service
      license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    host: api.am.wso2.com
    basePath: /api/runtime/1.0.0
    schemes:
     - https
     - http
    security:
     -
      default: []
    paths:
      /api/runtime/apis:
        Get:
          responses:
            "200":
              description: Successful operation
            "400":
              description: Not found