name: Run Gateway Integration Tests.
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
      - opened
      - synchronize
    paths:
      - '**/test/**'
      - '**/adapter/**'
      - '**/gateway/enforcer/**'
      - '**/gateway/router**'
concurrency:
  group: test-${{ github.event.number }}
  cancel-in-progress: true
env:
  GH_TOKEN: ${{ secrets.WSO2_BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Install Revive
        shell: sh
        run: |
          go install github.com/mgechev/revive@latest
      - name: Checkout apk-repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"
          path: apk-repo
          token: ${{ secrets.WSO2_BOT_TOKEN }}
      - name: Set release username and email
        shell: sh
        run: |
          git config --global user.name ${{ secrets.WSO2_BOT_USER }}
          git config --global user.email ${{ secrets.WSO2_BOT_EMAIL }}
      - name: checkout pull request and merge.
        shell: sh
        if: github.event_name == 'pull_request_target' && github.event.action == 'opened' || github.event.action == 'synchronize'
        run: |
          cd apk-repo
          gh pr checkout ${{ github.event.number }} -b pr-${{ github.event.number }}
          git checkout pr-${{ github.event.number }}
          git merge origin/main
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 all-http-methods-for-wildcard.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 backend-base-path.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 path-param-api.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 gateway-integration-test-infra.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 no-base-path.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 diff-listner-api.test.api.am.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 disable-api-security.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 disable-resource-security.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 prod-api.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 sand-api.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 resource-scopes.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 trailing-slash.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 interceptor-api.test.gw.wso2.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 interceptor-resource.test.gw.wso2.com" | sudo tee -a /etc/hosts
      - name: Run Integration Tests
        run: |
          cd apk-repo/test/integration
          ./gradlew build
